<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>9a2a1b0e-1226-4add-beb3-f0c76571fea8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='home']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;home&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;home&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>03161987-740a-4109-a6fe-e90dba89dfd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/sites/default/files/logo/cern-logo.png</value>
      <webElementGuid>cadf9c75-0034-4818-9bfe-0b3ac5ce8cef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>home</value>
      <webElementGuid>fc1ef978-bdf7-4abf-a4de-a2600d28abda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;js&quot;]/body[@class=&quot;page-node-189869 page-node-type-news_page cern-theme-on path-node page-node-type-news-page has-glyphicons no-admin-toolbar cern-toolbar&quot;]/div[@class=&quot;dialog-off-canvas-main-canvas&quot;]/header[1]/div[@class=&quot;header-wrapper&quot;]/div[@class=&quot;site-info col-xs-12 col-sm-2 col-md-3 col-lg-4&quot;]/div[@class=&quot;site-info__logo col-lg-3 col-md-3 col-sm-3&quot;]/a[1]/img[1]</value>
      <webElementGuid>b1a450d3-8439-4d92-9d5c-6d3be7c7111d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='home']</value>
      <webElementGuid>4468197d-24c3-4185-9bd3-884bd77c8fe5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>fc8f437e-2f51-49ee-9a81-a10b5814d99b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/sites/default/files/logo/cern-logo.png' and @alt = 'home']</value>
      <webElementGuid>5f7ee52b-b740-42ee-9788-86ecced6e8cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
